services:
  - type: web
    plan: free
    name: ipp-5
    runtime: docker
    repo: https://github.com/EGO-R/ipp-5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_SCHEMA
        fromDatabase:
          name: database
          property: database
      - key: DB_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}

databases:
  - name: database
    plan: free