spring:
  application:
    name: ipp-5
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ipp_5}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Egor2004}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false